// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeL_k7u0Kv-Uifq8YChgJOdN3d98QzpmQ',
    appId: '1:357664345657:web:d9135060f72e3d82f847e8',
    messagingSenderId: '357664345657',
    projectId: 'instagram-clone-11bfe',
    authDomain: 'instagram-clone-11bfe.firebaseapp.com',
    storageBucket: 'instagram-clone-11bfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq8xdgeVfgoXQ6q8fIPOZXjnVPG5RRnqk',
    appId: '1:357664345657:android:c201f134aa11923df847e8',
    messagingSenderId: '357664345657',
    projectId: 'instagram-clone-11bfe',
    storageBucket: 'instagram-clone-11bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWh47RYe1S7QUE3eub1ltSPZOvMAbcgBw',
    appId: '1:357664345657:ios:2abc682cdde0304df847e8',
    messagingSenderId: '357664345657',
    projectId: 'instagram-clone-11bfe',
    storageBucket: 'instagram-clone-11bfe.appspot.com',
    iosBundleId: 'com.example.insta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWh47RYe1S7QUE3eub1ltSPZOvMAbcgBw',
    appId: '1:357664345657:ios:3cc7df2f0e24230ef847e8',
    messagingSenderId: '357664345657',
    projectId: 'instagram-clone-11bfe',
    storageBucket: 'instagram-clone-11bfe.appspot.com',
    iosBundleId: 'com.example.insta.RunnerTests',
  );
}
